In [12]:
import duckdb
import pandas as pd

In [13]:
con = duckdb.connect(database='../data/nba.sqlite', read_only=False)
df = con.query("show tables").fetchdf()
df

                   name
0    common_player_info
1   draft_combine_stats
2         draft_history
3                  game
4             game_info
5          game_summary
6      inactive_players
7            line_score
8             officials
9           other_stats
10         play_by_play
11               player
12                 team
13         team_details
14         team_history
15     team_info_common

In [ ]:
## get game-ids

df = con.query("select * from play_by_play limit 2").fetchdf()
df

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,...,player2_team_nickname,player2_team_abbreviation,person3type,player3_id,player3_name,player3_team_id,player3_team_city,player3_team_nickname,player3_team_abbreviation,video_available_flag
0,0029600012,0,12,0,1,14:43 PM,12:00,None,Start of 1st Period (14:43 PM EST),None,...,None,None,0.0,0,None,None,None,None,None,0
1,0029600012,2,10,0,1,14:50 PM,12:00,Jump Ball O'Neal vs. Kleine: Tip to Cassell,None,None,...,Suns,PHX,5.0,208,Sam Cassell,1610612756.0,Phoenix,Suns,PHX,0

In [15]:
df = con.query("select * from play_by_play where game_id = '0029600012'").fetchdf()

In [16]:
df.head(30)

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,...,player2_team_nickname,player2_team_abbreviation,person3type,player3_id,player3_name,player3_team_id,player3_team_city,player3_team_nickname,player3_team_abbreviation,video_available_flag
0,0029600012,0,12,0,1,14:43 PM,12:00,None,Start of 1st Period (14:43 PM EST),None,...,None,None,0.0,0,None,None,None,None,None,0
1,0029600012,2,10,0,1,14:50 PM,12:00,Jump Ball O'Neal vs. Kleine: Tip to Cassell,None,None,...,Suns,PHX,5.0,208,Sam Cassell,1610612756.0,Phoenix,Suns,PHX,0
2,0029600012,3,2,1,1,14:51 PM,11:45,None,None,MISS Cassell 15' Jump Shot,...,None,None,0.0,0,None,None,None,None,None,0
3,0029600012,4,4,0,1,14:51 PM,11:43,O'Neal REBOUND (Off:0 Def:1),None,None,...,None,None,0.0,0,None,None,None,None,None,0
4,0029600012,5,2,1,1,14:51 PM,11:29,MISS Ceballos 26' 3PT Jump Shot,None,None,...,None,None,0.0,0,None,None,None,None,None,0
5,0029600012,6,4,0,1,14:51 PM,11:27,None,None,Cassell REBOUND (Off:0 Def:1),...,None,None,0.0,0,None,None,None,None,None,0
6,0029600012,7,6,1,1,14:51 PM,11:14,Van Exel P.FOUL (P1.T1),None,None,...,None,None,0.0,0,None,None,None,None,None,0
7,0029600012,8,5,1,1,14:52 PM,11:08,None,None,Cassell Bad Pass Turnover (P1.T1),...,None,None,0.0,0,None,None,None,None,None,0
8,0029600012,9,2,5,1,14:52 PM,10:49,MISS Ceballos 1' Layup,None,Horry BLOCK (1 BLK),...,None,None,5.0,109,Robert Horry,1610612756.0,Phoenix,Suns,PHX,0
9,0029600012,10,4,0,1,14:52 PM,10:49,LAKERS Rebound,None,None,...,None,None,0.0,0,None,None,None,None,None,0
10,0029600012,11,5,2,1,14:52 PM,10:45,Ceballos Lost Ball Turnover (P1.T1),None,Horry STEAL (1 STL),...,Suns,PHX,0.0,0,None,None,None,None,None,0
11,0029600012,12,5,1,1,14:52 PM,10:42,Van Exel STEAL (1 STL),None,Horry Bad Pass Turnover (P1.T2),...,Lakers,LAL,0.0,0,None,None,None,None,None,0
12,0029600012,13,1,8,1,14:53 PM,10:40,O'Neal Slam Dunk (2 PTS) (Van Exel 1 AST),None,None,...,Lakers,LAL,0.0,0,None,None,None,None,None,0
13,0029600012,14,2,1,1,14:53 PM,10:19,None,None,MISS Kleine 11' Jump Shot,...,None,None,0.0,0,None,None,None,None,None,0
14,0029600012,15,4,0,1,14:53 PM,10:18,Ceballos REBOUND (Off:0 Def:1),None,None,...,None,None,0.0,0,None,None,None,None,None,0
15,0029600012,16,1,5,1,14:53 PM,10:05,Ceballos Layup (2 PTS) (Jones 1 AST),None,None,...,Lakers,LAL,0.0,0,None,None,None,None,None,0
16,0029600012,17,2,1,1,14:53 PM,9:42,None,None,MISS Person 16' Jump Shot,...,None,None,0.0,0,None,None,None,None,None,0
17,0029600012,18,4,0,1,14:53 PM,9:40,None,None,Kleine REBOUND (Off:1 Def:0),...,None,None,0.0,0,None,None,None,None,None,0
18,0029600012,19,2,1,1,14:54 PM,9:38,None,None,MISS Person 3PT Jump Shot,...,None,None,0.0,0,None,None,None,None,None,0
19,0029600012,20,4,0,1,14:54 PM,9:36,O'Neal REBOUND (Off:0 Def:2),None,None,...,None,None,0.0,0,None,None,None,None,None,0
20,0029600012,21,5,1,1,14:54 PM,9:32,Ceballos Bad Pass Turnover (P2.T2),None,Green STEAL (1 STL),...,Suns,PHX,0.0,0,None,None,None,None,None,0
21,0029600012,22,6,2,1,14:54 PM,9:24,Van Exel S.FOUL (P2.T2),None,None,...,None,None,0.0,0,None,None,None,None,None,0
22,0029600012,24,3,11,1,14:54 PM,9:24,None,None,Cassell Free Throw 1 of 2 (1 PTS),...,None,None,0.0,0,None,None,None,None,None,0
23,0029600012,25,8,0,1,14:54 PM,9:24,SUB: Fisher FOR Van Exel,None,None,...,Lakers,LAL,0.0,0,None,None,None,None,None,0
24,0029600012,26,3,12,1,14:54 PM,9:24,None,None,Cassell Free Throw 2 of 2 (2 PTS),...,None,None,0.0,0,None,None,None,None,None,0
25,0029600012,27,2,5,1,14:55 PM,9:13,MISS Ceballos Layup,None,Green BLOCK (1 BLK),...,None,None,5.0,920,A.C. Green,1610612756.0,Phoenix,Suns,PHX,0
26,0029600012,28,4,0,1,14:55 PM,9:11,None,None,Suns Rebound,...,None,None,0.0,0,None,None,None,None,None,0
27,0029600012,30,7,3,1,14:55 PM,8:53,Jones Violation:Lane,None,None,...,None,None,0.0,0,None,None,None,None,None,0
28,0029600012,29,1,5,1,14:55 PM,8:53,None,None,Person Layup (2 PTS) (Kleine 1 AST),...,Suns,PHX,4.0,0,None,1610612747.0,Los Angeles,Lakers,LAL,0
29,0029600012,31,6,2,1,14:56 PM,8:37,None,None,Kleine S.FOUL (P1.T1),...,Suns,PHX,0.0,0,None,None,None,None,None,0

In [17]:
df[["homedescription",	"neutraldescription"	,"visitordescription"]]

,homedescription,neutraldescription,visitordescription
0,None,Start of 1st Period (14:43 PM EST),None
1,Jump Ball O'Neal vs. Kleine: Tip to Cassell,None,None
2,None,None,MISS Cassell 15' Jump Shot
3,O'Neal REBOUND (Off:0 Def:1),None,None
4,MISS Ceballos 26' 3PT Jump Shot,None,None
...,...,...,...
461,None,None,MISS Manning Free Throw 1 of 2
462,None,None,Suns Rebound
463,None,None,MISS Manning Free Throw 2 of 2
464,Knight REBOUND (Off:0 Def:2),None,None
465,None,End of 4th Period (17:12 PM EST),None

In [18]:
df.columns

Index(['game_id', 'eventnum', 'eventmsgtype', 'eventmsgactiontype', 'period',
       'wctimestring', 'pctimestring', 'homedescription', 'neutraldescription',
       'visitordescription', 'score', 'scoremargin', 'person1type',
       'player1_id', 'player1_name', 'player1_team_id', 'player1_team_city',
       'player1_team_nickname', 'player1_team_abbreviation', 'person2type',
       'player2_id', 'player2_name', 'player2_team_id', 'player2_team_city',
       'player2_team_nickname', 'player2_team_abbreviation', 'person3type',
       'player3_id', 'player3_name', 'player3_team_id', 'player3_team_city',
       'player3_team_nickname', 'player3_team_abbreviation',
       'video_available_flag'],
      dtype='object')

In [19]:

## Pseudo logic for aggregation of player counting stats


# from collections import Counter

# players = Counter()

# for game in games:
#     for event in game.events:
#         player = event.player
#         stat = event.stat
#         players[player[stat]] += 1